// 임시 데이터
export const activities: Activity[] = [
  {
    id: 1,
    title: '피오르 체험',
    price: 42800,
    imageUrl: '/image/ActivityImageSample/atvt-img1.png',
    rating: 3.9,
  },
  {
    id: 2,
    title: '해안가 마을에서 1주의 삶',
    price: 217000,
    imageUrl: '/image/ActivityImageSample/atvt-img2.png',
    rating: 2.9,
  },
  {
    id: 3,
    title: '부모님과 함께 곤돌라 체험',
    price: 6000,
    imageUrl: '/image/ActivityImageSample/atvt-img3.png',
    rating: 4.0,
  },
  {
    id: 4,
    title: '열기구 페스티벌',
    price: 35000,
    imageUrl: '/image/ActivityImageSample/atvt-img4.png',
    rating: 4.1,
  },
  {
    id: 5,
    title: '베트남 자전거 여행',
    price: 42800,
    imageUrl: '/image/ActivityImageSample/atvt-img5.png',
    rating: 3.9,
    reviewCount: 108,
  },
  {
    id: 6,
    title: '다양한 열대어 구경하기',
    price: 217000,
    imageUrl: '/image/ActivityImageSample/atvt-img6.png',
    rating: 2.9,
    reviewCount: 67,
  },
  {
    id: 7,
    title: '세상에서 가장 멋진 석양',
    price: 6000,
    imageUrl: '/image/ActivityImageSample/atvt-img7.png',
    rating: 4.0,
    reviewCount: 113,
  },
  {
    id: 8,
    title: '여행 가이드와 함께하는 숲',
    price: 35000,
    imageUrl: '/image/ActivityImageSample/atvt-img8.png',
    rating: 4.1,
    reviewCount: 85,
  },
  {
    id: 9,
    title: '피오르 체험2',
    price: 42800,
    imageUrl: '/image/ActivityImageSample/atvt-img1.png',
    rating: 3.9,
  },
  {
    id: 10,
    title: '해안가 마을에서 1주의 삶2',
    price: 217000,
    imageUrl: '/image/ActivityImageSample/atvt-img2.png',
    rating: 2.9,
  },
  {
    id: 11,
    title: '부모님과 함께 곤돌라 체험2',
    price: 6000,
    imageUrl: '/image/ActivityImageSample/atvt-img3.png',
    rating: 4.0,
  },
  {
    id: 12,
    title: '열기구 페스티벌2',
    price: 35000,
    imageUrl: '/image/ActivityImageSample/atvt-img4.png',
    rating: 4.1,
  },
  {
    id: 13,
    title: '베트남 자전거 여행2',
    price: 42800,
    imageUrl: '/image/ActivityImageSample/atvt-img5.png',
    rating: 3.9,
    reviewCount: 108,
  },
  {
    id: 14,
    title: '다양한 열대어 구경하기2',
    price: 217000,
    imageUrl: '/image/ActivityImageSample/atvt-img6.png',
    rating: 2.9,
    reviewCount: 67,
  },
  {
    id: 15,
    title: '세상에서 가장 멋진 석양2',
    price: 6000,
    imageUrl: '/image/ActivityImageSample/atvt-img7.png',
    rating: 4.0,
    reviewCount: 113,
  },
  {
    id: 16,
    title: '여행 가이드와 함께하는 숲2',
    price: 35000,
    imageUrl: '/image/ActivityImageSample/atvt-img8.png',
    rating: 4.1,
    reviewCount: 85,
  },
  {
    id: 17,
    title: '피오르 체험3',
    price: 42800,
    imageUrl: '/image/ActivityImageSample/atvt-img1.png',
    rating: 3.9,
  },
  {
    id: 18,
    title: '해안가 마을에서 1주의 삶3',
    price: 217000,
    imageUrl: '/image/ActivityImageSample/atvt-img2.png',
    rating: 2.9,
  },
  {
    id: 19,
    title: '부모님과 함께 곤돌라 체험3',
    price: 6000,
    imageUrl: '/image/ActivityImageSample/atvt-img3.png',
    rating: 4.0,
  },
  {
    id: 20,
    title: '열기구 페스티벌3',
    price: 35000,
    imageUrl: '/image/ActivityImageSample/atvt-img4.png',
    rating: 4.1,
  },
  {
    id: 21,
    title: '베트남 자전거 여행3',
    price: 42800,
    imageUrl: '/image/ActivityImageSample/atvt-img5.png',
    rating: 3.9,
    reviewCount: 108,
  },
  {
    id: 22,
    title: '다양한 열대어 구경하기3',
    price: 217000,
    imageUrl: '/image/ActivityImageSample/atvt-img6.png',
    rating: 2.9,
    reviewCount: 67,
  },
  {
    id: 23,
    title: '세상에서 가장 멋진 석양3',
    price: 6000,
    imageUrl: '/image/ActivityImageSample/atvt-img7.png',
    rating: 4.0,
    reviewCount: 113,
  },
  {
    id: 24,
    title: '여행 가이드와 함께하는 숲3',
    price: 35000,
    imageUrl: '/image/ActivityImageSample/atvt-img8.png',
    rating: 4.1,
    reviewCount: 85,
  },
];
