import { HotActivityCardProps } from '@/types/mainPage/HotActivityCardTypes';

export const hotActivities: HotActivityCardProps[] = [
  {
    id: 1,
    image: '/image/mainBanner01.png',
    rating: 4.9,
    reviews: 793,
    title: '함께 배우며 즐거운 스트릿 댄스',
    price: 38000,
  },
  {
    id: 2,
    image: '/image/mainBanner02.png',
    rating: 4.9,
    reviews: 593,
    title: '연인과 사랑의 징검다리 건너기',
    price: 5600,
  },
  {
    id: 3,
    image: '/image/mainBanner03.png',
    rating: 4.9,
    reviews: 293,
    title: '부모님과 함께\n갈대숲 체험',
    price: 38000,
  },
  {
    id: 4,
    image: '/image/mainBanner04.png',
    rating: 4.8,
    reviews: 1024,
    title: '나만의 도자기 만들기 체험',
    price: 45000,
  },
  {
    id: 5,
    image: '/image/mainBanner05.png',
    rating: 4.7,
    reviews: 850,
    title: '전통 한복 입고 사진 촬영',
    price: 30000,
  },
  {
    id: 6,
    image: '/image/mainBanner06.png',
    rating: 4.9,
    reviews: 1200,
    title: '한강에서 요가 클래스',
    price: 20000,
  },
  {
    id: 7,
    image: '/image/mainBanner07.png',
    rating: 4.8,
    reviews: 670,
    title: '이색 칵테일 만들기 클래스',
    price: 40000,
  },
  {
    id: 8,
    image: '/image/mainBanner08.png',
    rating: 4.9,
    reviews: 910,
    title: '쿠킹 클래스: 이탈리안 요리 만들기',
    price: 55000,
  },
  {
    id: 9,
    image: '/image/mainBanner09.png',
    rating: 4.6,
    reviews: 320,
    title: '캠핑장에서 별보기 체험',
    price: 15000,
  },
  {
    id: 10,
    image: '/image/mainBanner10.png',
    rating: 5.0,
    reviews: 150,
    title: '전통 차 체험 클래스',
    price: 25000,
  },
];
